export const MOVE_TO = 'MOVE_TO'
export const GOTO_BACK = 'GOTO_BACK'
export const GOTO_FORWARD = 'GOTO_FORWARD'
export const INIT_LEVEL = 'INIT_LEVEL'
export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCH_LEVELS = 'FETCH_LEVELS'
export const ERROR = 'ERROR'
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME'