// Login mutation types
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_CHECK_REQUEST = 'LOGIN_CHECK_REQUEST'
export const LOGIN_CHECK_SUCCESS = 'LOGIN_CHECK_SUCCESS'
export const LOGIN_CHECK_SUCCESS_EXPIRED_TOKEN = 'LOGIN_CHECK_SUCCESS_EXPIRED_TOKEN'
export const LOGIN_CHECK_FAILURE = 'LOGIN_CHECK_FAILURE'

// Logout mutation types
export const LOGOUT = 'LOGOUT'

// Fetch data mutation types
export const FETCH_LEVELS_REQUEST = 'FETCH_LEVELS_REQUEST'
export const FETCH_LEVELS_SUCCESS = 'FETCH_LEVELS_SUCCESS'
export const FETCH_LEVELS_FAILURE = 'FETCH_LEVELS_FAILURE'
export const GET_LEVEL_INFO_REQUEST = 'GET_LEVEL_INFO_REQUEST'
export const GET_LEVEL_INFO_SUCCESS = 'GET_LEVEL_INFO_SUCCESS'
export const GET_LEVEL_INFO_FAILURE = 'GET_LEVEL_INFO_FAILURE'

// Post data mutation types
export const REPORT_SOLUTION_REQUEST = 'REPORT_SOLUTION_REQUEST'
export const REPORT_SOLUTION_SUCCESS = 'REPORT_SOLUTION_SUCCESS'
export const REPORT_SOLUTION_FAILURE = 'REPORT_SOLUTION_FAILURE'

// Game mutation types
export const MOVE_TO = 'MOVE_TO'
export const GOTO_BACK = 'GOTO_BACK'
export const GOTO_FORWARD = 'GOTO_FORWARD'
