
export default {
    boards: [
        {
            rows: 5,
            columns: 5,
            walls: [
                {row: 1, column: 1},
                {row: 1, column: 2},
                {row: 1, column: 3},
                {row: 1, column: 4},
                {row: 1, column: 5},
                {row: 2, column: 1},
                {row: 2, column: 5},
                {row: 3, column: 1},
                {row: 3, column: 5},
                {row: 4, column: 1},
                {row: 4, column: 5},
                {row: 5, column: 1},
                {row: 5, column: 2},
                {row: 5, column: 3},
                {row: 5, column: 4},
                {row: 5, column: 5},
            ],
            brickTargets: [
                {row: 2, column: 2}
            ],
            playerInitialPosition: {
                row: 2,
                column: 2
            },
            bricksInitialPosition: [
                {row: 3, column: 3}
            ]
        },
        {
            rows: 8,
            columns: 7,
            walls: [
                {row: 1, column: 4},
                {row: 1, column: 5},
                {row: 1, column: 6},
                {row: 1, column: 7},
                {row: 2, column: 4},
                {row: 2, column: 7},
                {row: 3, column: 4},
                {row: 3, column: 7},
                {row: 4, column: 4},
                {row: 4, column: 7},
                {row: 5, column: 1},
                {row: 5, column: 2},
                {row: 5, column: 3},
                {row: 5, column: 4},
                {row: 5, column: 7},
                {row: 6, column: 1},
                {row: 6, column: 7},
                {row: 7, column: 1},
                {row: 7, column: 7},
                {row: 8, column: 1},
                {row: 8, column: 2},
                {row: 8, column: 3},
                {row: 8, column: 4},
                {row: 8, column: 5},
                {row: 8, column: 6},
                {row: 8, column: 7},
            ],
            brickTargets: [
                {row: 4, column: 6},
                {row: 7, column: 4}
            ],
            playerInitialPosition: {
                row: 7,
                column: 2
            },
            bricksInitialPosition: [
                {row: 4, column: 5},
                {row: 7, column: 3}
            ]
        },
        {
            rows: 13,
            columns: 17,
            walls: [
                {row: 1, column: 2},
                {row: 1, column: 3},
                {row: 1, column: 4},
                {row: 1, column: 5},
                {row: 1, column: 6},
                {row: 1, column: 7},
                {row: 1, column: 8},
                {row: 1, column: 9},
                {row: 1, column: 10},
                {row: 1, column: 11},
                {row: 1, column: 12},
                {row: 2, column: 1},
                {row: 2, column: 2},
                {row: 2, column: 12},
                {row: 2, column: 13},
                {row: 3, column: 1},
                {row: 3, column: 13},
                {row: 4, column: 1},
                {row: 4, column: 4},
                {row: 4, column: 6},
                {row: 4, column: 8},
                {row: 4, column: 10},
                {row: 4, column: 13},
                {row: 5, column: 1},
                {row: 5, column: 6},
                {row: 5, column: 8},
                {row: 5, column: 13},
                {row: 5, column: 14},
                {row: 5, column: 15},
                {row: 5, column: 16},
                {row: 5, column: 17},
                {row: 6, column: 1},
                {row: 6, column: 4},
                {row: 6, column: 5},
                {row: 6, column: 6},
                {row: 6, column: 8},
                {row: 6, column: 9},
                {row: 6, column: 10},
                {row: 6, column: 13},
                {row: 6, column: 17},
                {row: 7, column: 1},
                {row: 7, column: 17},
                {row: 8, column: 1},
                {row: 8, column: 4},
                {row: 8, column: 5},
                {row: 8, column: 6},
                {row: 8, column: 8},
                {row: 8, column: 9},
                {row: 8, column: 10},
                {row: 8, column: 13},
                {row: 8, column: 17},
                {row: 9, column: 1},
                {row: 9, column: 6},
                {row: 9, column: 8},
                {row: 9, column: 13},
                {row: 9, column: 14},
                {row: 9, column: 15},
                {row: 9, column: 16},
                {row: 9, column: 17},
                {row: 10, column: 1},
                {row: 10, column: 4},
                {row: 10, column: 6},
                {row: 10, column: 8},
                {row: 10, column: 10},
                {row: 10, column: 13},
                {row: 11, column: 1},
                {row: 11, column: 13},
                {row: 12, column: 1},
                {row: 12, column: 2},
                {row: 12, column: 12},
                {row: 12, column: 13},
                {row: 13, column: 2},
                {row: 13, column: 3},
                {row: 13, column: 4},
                {row: 13, column: 5},
                {row: 13, column: 6},
                {row: 13, column: 7},
                {row: 13, column: 8},
                {row: 13, column: 9},
                {row: 13, column: 10},
                {row: 13, column: 11},
                {row: 13, column: 12},
            ],
            brickTargets: [
                { row: 4, column: 7},
                { row: 5, column: 7},
                { row: 6, column: 7},
                { row: 7, column: 4},
                { row: 7, column: 5},
                { row: 7, column: 6},
                { row: 7, column: 8},
                { row: 7, column: 9},
                { row: 7, column: 10},
                { row: 8, column: 7},
                { row: 9, column: 7},
                { row: 10, column: 7},
            ],
            playerInitialPosition: {
                row: 7,
                column: 7
            },
            bricksInitialPosition: [
                { row: 3, column: 4},
                { row: 3, column: 10},
                { row: 4, column: 3},
                { row: 4, column: 11},
                { row: 5, column: 7},
                { row: 7, column: 5},
                { row: 7, column: 9},
                { row: 9, column: 7},
                { row: 10, column: 3},
                { row: 10, column: 11},
                { row: 11, column: 4},
                { row: 11, column: 10}
            ]
        },
    ],
    currentBoardIndex: -1,
    playerCurrentPosition: {
        /*row: 2,
        column: 2
    */},
    bricksCurrentPosition: [
        /*{row: 3, column: 3} */
    ],
    numberMovements: 0,
    numberMovementsPlayed: 0,
    listMovements: [
        /* { direction: left|right|down|up, movesBrick: true|false } */
    ],
    levelCompleted: false
}
  